### Basics of tensorflow, Tensors, Variables, Placeholders & Operations. 

In [1]:
import tensorflow as tf

##### Constants & Operations
First things first, lets create two constants and add them.

In [2]:
a = tf.constant([40])
b = tf.constant([2])

In [3]:
c = tf.add(a,b)
# c = a + b 

Remember that Tensorflow works by defining a computation graph, meaning the value of [c] is not computed on the above line, but rather stored as a computation to do. If we want to access the value of [c] we first have to have the computation graph in a <em> session </em> 

Note: we can use the regular python notation c = a + b, or the tensorflow function tf.add()

In [4]:
with tf.Session() as sess:
  result = sess.run(c)
  print(result)

[42]


In [5]:
d = tf.constant([6])
e = tf.constant([7])

In [6]:
f = tf.multiply(d,e)

In [7]:
with tf.Session() as sess:
  result = sess.run(f)
  print(result)

[42]


This is the basic idea of running a tensorflow session. Tensorflow support many more operations for tensors (..if you couldn't guess from the name)

Here are a few examples.  
* tf.multiply(x, y)
* tf.div(x, y)
* tf.square(x) 
* tf.sqrt(x)
* tf.pow(x, y)
* tf.exp(x)
* tf.log(x)
* tf.cos(x)
* tf.sin(x)

Creating integer constants is the same as for vectors, marticies and tensors.   
(Remember a single number is considered a rank-zero tensor, a vector is rank-one, a matrix is rank-two and so forth)

In [8]:
A = tf.constant([[1,2,3],[3,4,5],[5,6,7]])
B = tf.constant([[3,4,5],[5,6,7],[7,8,9]])

In [9]:
C = tf.add(A,B)

In [10]:
with tf.Session() as sess:
    result = sess.run(C)
    print(result)
    

[[ 4  6  8]
 [ 8 10 12]
 [12 14 16]]


There we see elementwise addition on two 3x3 matricies. One thing to keep in mind while using operators in tensorflow what we mean by these mathmatical operations. Finding the product ab = 6 x 7 = 42 is straightforward, but depending on who you ask you may have different answers for what the product AB would give you.  
The two obvious answers are:
1. Elementwise multiplication, called the Hammard product  
2. The matrix product, as in linear algebra.

Both can easily be expressed in tensorflow 

In [11]:
C_one = tf.matmul(A,B)
C_two = tf.multiply(A,B)

In [12]:
with tf.Session() as sess:
    op_one = sess.run(C_one)
    op_two = sess.run(C_two)
    print("The Hammard product:\n{} \nThe matrix product:\n{}".format(op_one,op_two))

The Hammard product:
[[ 34  40  46]
 [ 64  76  88]
 [ 94 112 130]] 
The matrix product:
[[ 3  8 15]
 [15 24 35]
 [35 48 63]]


#### Creating and updating variables

In [13]:
a = tf.constant(10)
b = tf.Variable(0)
init_op = tf.global_variables_initializer()
update = tf.assign(b,a)

In [14]:
with tf.Session() as sess:
    sess.run(init_op)
    sess.run(update)
    result = sess.run(b)
    print(result)

10


#### Fibonacci Sequence 
We have now covered enough to express the Fibonacci sequence using tensorflow.
The Fibonacci sequence is defined by the recursize equation,
\begin{equation} 
F_n = F_{n-1} + F_{n-2}
\end{equation}
Which produces the series, 1,1,2,3,5,8,13,21...


In [15]:
f_n = tf.Variable(0)
f_n_minus_one = tf.Variable(1)
f_n_minus_two = tf.Variable(1)
steps = 17
init_op = tf.global_variables_initializer()
update1 = tf.assign(f_n,f_n_minus_one+f_n_minus_two)
update2 = tf.assign(f_n_minus_two,f_n_minus_one)
update3 = tf.assign(f_n_minus_one,f_n)


In [16]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(f_n_minus_two),end=', ')
    print(sess.run(f_n_minus_one),end=', ')
    for i in range(steps):
        sess.run(update1)
        sess.run(update2)
        sess.run(update3)
        print(sess.run(f_n),end=', ')
    print('.....')

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, .....
